### PR TITLE
feat: add web front-end to check Arkadroid elegibility

### PR DESCRIPTION
**Pull request by YannisDC**

### CODE REVIEW

**Comment by philiphacks** [comment]
This is done.

Only three things need to happen

- Add sign in/out button to header instead of current awkward positioning
- Fix footer with real logo and links to whitepaper
- Make more contrast between being eligible and not

Something for @Macxim

**Comment by Macxim** [comment]
A couple of questions: @YannisDC @philipdesmedt 

- Why loading fonts as .ttf?
- It's probably better to make an SVG for the "Arkadroids" main title in the header instead of loading a font that you won't use anywhere else.
- Also that 5 font-family, thay may be a bit too much 😅 
- How do I know if I'm eligible or not? Connecting the wallet doesn't make any difference apart saying that the wallet is connected.
- In the footer, in Protocol, the first Byzantion link leads to Arkadiko whitepaper
- In the footer, Misc section is empty
- We could use the purple shadow for titles elsewhere to have a more consistent look
- We could have more section to separate content a little bit better: Eligibility, Arkadroids (for example)
- Blue border on top of footer could reuse that purple shade, instead of the blue that literally comes out of the blue

Do you need my help for this? Or do you want me to do all this?

**Comment by philiphacks** [comment]
@Macxim feel free to change all these fonts and optimise with SVGs etc :)
Can you also fix the footer and the links?
Generally you can clean up the whole layout as you wish TBH :)

As for the eligibility, that's what I'm saying.. perhaps there's contrast, but it's not clear when you're not eligible and when you are.
1. Eligible (purple glow)
image

2. Not eligible (no glow)
image

**Comment by Macxim** [comment]
Gotcha, will make changes as soon as possible.

**Comment by Macxim** [comment]
Can you guys please check? @YannisDC @philipdesmedt @nieldeckx 
Feedback welcome.

**Comment by Macxim** [comment]
localhost_9000_ (1)

**Comment by Macxim** [comment]
IMO we should still add a list of all the eligible Arkadroids in a box once wallet is connected, not only having the cards glowing.

**Comment by philiphacks** [comment]
@Macxim agree the eligibility is still not very clear.. but gonna merge this and we can still improve if we want later

**Pull request merged**
